name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3 for Node.js 20 support

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated to v3 for Node.js 20 support

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2  # Ensures Node.js 20 support
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/docker-image-repo:latest

    - name: Post Log Details
      run: echo "Image build and push step completed"
      if: always()
